# inherit_from: .rubocop_todo.yml
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
